### ISSUE TITLE
CatColab v0.1

### ISSUE THREAD

**Issue by epatters** [ToposInstitute/CatColab#173]
- [x] Include minimal branding in toolbar (#191)
- [x] Use Topos logo for favicon (#174)
- [x] Extend the repo README with short section for category theorists (#177)
- [x] Warn or fix about Safari issues (#195)
- [x] Remove "Loading" text from frontend (#198)
- [x] Create a help/info/about page within CatColab (#183, #201)
- [x] Write a blog post introducing the project (being written by @KevinDCarlson on the Topos blog)
